#include "ai_factory/cuda/hull_white/caplets.cuh"
#include "ai_factory/common/fixed_income/hull_white.hpp"
#include "ai_factory/cuda/common/philox.cuh"
#include "ai_factory/cuda/common/reductions.cuh"
#include "ai_factory/cuda/common/runtime.cuh"
namespace ai_factory::cuda {namespace {struct Tag{};struct Coefficients{double state_scale,integral_loading,residual_scale,deterministic_integral,bond_a,bond_b;};
__global__ void kernel(const HullWhiteCapletRow*rows,std::size_t count,std::size_t paths,MonteCarloOutput*outputs){const auto i=static_cast<std::size_t>(blockIdx.x);if(i>=count)return;const auto r=rows[i];const auto&p=r.product;__shared__ Coefficients c;if(threadIdx.x==0){const double sv=fixed_income::hull_white_state_variance(r.mean_reversion,r.volatility,p.fixing_time),iv=fixed_income::hull_white_integral_variance(r.mean_reversion,r.volatility,p.fixing_time),cov=fixed_income::hull_white_state_integral_covariance(r.mean_reversion,r.volatility,p.fixing_time);c.state_scale=sqrt(sv);c.integral_loading=cov/c.state_scale;c.residual_scale=sqrt(fmax(iv-c.integral_loading*c.integral_loading,0.0));c.deterministic_integral=fixed_income::hull_white_deterministic_integral(p.fixing_time,r.mean_reversion,r.volatility,r.beta0,r.beta1,r.beta2,r.tau);c.bond_a=fixed_income::hull_white_bond_a(p.fixing_time,p.fixing_time+p.accrual_period,r.mean_reversion,r.volatility,r.beta0,r.beta1,r.beta2,r.tau);c.bond_b=fixed_income::hull_white_b(r.mean_reversion,p.accrual_period);}__syncthreads();double sum=0,sumsq=0;for(std::size_t path=threadIdx.x;path<paths;path+=blockDim.x){const auto z=rng::standard_normal_pair(r.seed,0U,path);const double state=c.state_scale*z.first,integral=c.integral_loading*z.first+c.residual_scale*z.second,bond=c.bond_a*exp(-c.bond_b*state),payoff=exp(-c.deterministic_integral-integral)*p.notional*fmax(1-(1+p.accrual_period*p.strike)*bond,0.0);sum+=payoff;sumsq+=payoff*payoff;}reductions::reduce_block(sum,sumsq);if(threadIdx.x==0){extern __shared__ double shared[];const double n=static_cast<double>(paths),mean=shared[0]/n,var=(shared[blockDim.x]-n*mean*mean)/(n-1);outputs[i]={mean,sqrt(fmax(var,0.0)/n)};}}
}
void price_hull_white_caplet_cuda(const HullWhiteCapletRow*h,std::size_t n,std::size_t paths,MonteCarloOutput*out,CudaTiming*t){auto&w=detail::reusable_cuda_workspace<Tag,2>();auto*r=w.buffer<HullWhiteCapletRow>(0,n,"caplet rows");auto*o=w.buffer<MonteCarloOutput>(1,n,"caplet outputs");detail::check_cuda(cudaMemcpy(r,h,n*sizeof(*h),cudaMemcpyHostToDevice),"copy rows");detail::check_cuda(cudaEventRecord(w.start_event()),"start");kernel<<<static_cast<unsigned>(n),detail::kThreadsPerBlock,2*detail::kThreadsPerBlock*sizeof(double)>>>(r,n,paths,o);detail::check_cuda(cudaGetLastError(),"Hull-White caplet kernel");detail::check_cuda(cudaEventRecord(w.stop_event()),"stop");detail::check_cuda(cudaEventSynchronize(w.stop_event()),"sync");float ms=0;detail::check_cuda(cudaEventElapsedTime(&ms,w.start_event(),w.stop_event()),"elapsed");detail::check_cuda(cudaMemcpy(out,o,n*sizeof(*out),cudaMemcpyDeviceToHost),"copy outputs");if(t)t->simulation_ms=t->total_ms=ms;}
}
