# Host and CUDA contract tests for the selectable price-gradient integration.
add_executable(test_price_gradients_launch_plan EXCLUDE_FROM_ALL tests/price_gradients/launch_plan_test.cpp)
target_include_directories(test_price_gradients_launch_plan PRIVATE ${CMAKE_SOURCE_DIR})
target_link_libraries(test_price_gradients_launch_plan PRIVATE ai_factory_cuda_tuning nlohmann_json::nlohmann_json)
target_compile_features(test_price_gradients_launch_plan PRIVATE cxx_std_23)
add_dependencies(ai_factory_host_tests test_price_gradients_launch_plan)
add_test(NAME price_gradients_launch_plan COMMAND test_price_gradients_launch_plan)
set_tests_properties(price_gradients_launch_plan PROPERTIES LABELS "workbench;price_gradients;offline" TIMEOUT 30)
add_executable(test_price_gradients_configuration EXCLUDE_FROM_ALL
    tests/price_gradients/configuration_test.cpp)
ai_factory_configure_host_library(test_price_gradients_configuration)
add_dependencies(ai_factory_host_tests test_price_gradients_configuration)
add_test(NAME price_gradients_configuration COMMAND test_price_gradients_configuration)
set_tests_properties(price_gradients_configuration PROPERTIES
    LABELS "workbench;price_gradients;offline" TIMEOUT 30)
add_cuda_workbench_test(price_gradients_european_cuda
    tests/price_gradients/european_cuda_test.cu "price_gradients;parity" 120)
add_cuda_workbench_test(price_gradients_central_work_cuda
    tests/price_gradients/central_work_cuda_test.cu "price_gradients;work_counts" 60)
add_cuda_workbench_test(price_gradients_cev_cuda
    tests/price_gradients/cev_cuda_test.cu "price_gradients;parity;cev" 120)
add_cuda_workbench_test(price_gradients_merton_cuda
    tests/price_gradients/merton_cuda_test.cu "price_gradients;parity;merton" 120)
add_cuda_workbench_test(price_gradients_american_cuda
    tests/price_gradients/american_cuda_test.cu
    "price_gradients;parity;american_option;longstaff_schwartz;heston" 180)
add_offline_stage_test(price_gradients_dataset ai_factory_price_gradient_dataset tests/price_gradients/dataset_test.cpp)
if(Python3_Interpreter_FOUND)
    add_test(NAME price_gradients_artifact_contract COMMAND ${Python3_EXECUTABLE} -m unittest discover
        -s tests/price_gradients -p "test_*.py")
    set_tests_properties(price_gradients_artifact_contract PROPERTIES
        WORKING_DIRECTORY ${CMAKE_SOURCE_DIR} LABELS "workbench;price_gradients;offline;codegen" TIMEOUT 30)
endif()

# Explicit performance executable; no timing thresholds in routine CTest.
add_executable(benchmark_price_gradients_batching EXCLUDE_FROM_ALL
    tests/performance/price_gradients/batching.cu)
target_include_directories(benchmark_price_gradients_batching PRIVATE ${CMAKE_SOURCE_DIR})
target_link_libraries(benchmark_price_gradients_batching PRIVATE ai_factory_runtime
    ai_factory_equity_black_scholes_european_option_price_gradients
    ai_factory_equity_heston_european_option_price_gradients)
set_target_properties(benchmark_price_gradients_batching PROPERTIES CUDA_STANDARD 23 CUDA_STANDARD_REQUIRED YES)

add_executable(benchmark_price_gradients_closed_form EXCLUDE_FROM_ALL tests/performance/price_gradients/closed_form.cu)
target_include_directories(benchmark_price_gradients_closed_form PRIVATE ${CMAKE_SOURCE_DIR})
target_link_libraries(benchmark_price_gradients_closed_form PRIVATE ai_factory_runtime
    ai_factory_equity_black_scholes_european_option_price_gradients)
set_target_properties(benchmark_price_gradients_closed_form PROPERTIES CUDA_STANDARD 23 CUDA_STANDARD_REQUIRED YES)

# Explicit numerical experiment: no stochastic acceptance thresholds in routine CTest.
add_executable(study_price_gradients_bumps EXCLUDE_FROM_ALL tests/price_gradients/bump_study.cu)
target_include_directories(study_price_gradients_bumps PRIVATE ${CMAKE_SOURCE_DIR})
target_link_libraries(study_price_gradients_bumps PRIVATE ai_factory_runtime
    ai_factory_equity_black_scholes_european_option_price_gradients
    ai_factory_equity_heston_european_option_price_gradients
    ai_factory_equity_cev_european_option_price_gradients)
set_target_properties(study_price_gradients_bumps PROPERTIES CUDA_STANDARD 23 CUDA_STANDARD_REQUIRED YES)

add_executable(benchmark_price_gradients_cev EXCLUDE_FROM_ALL tests/performance/price_gradients/cev.cu)
target_include_directories(benchmark_price_gradients_cev PRIVATE ${CMAKE_SOURCE_DIR})
target_link_libraries(benchmark_price_gradients_cev PRIVATE ai_factory_runtime
    ai_factory_equity_cev_european_option_price_gradients ai_factory_equity_cev_european_option_price_delta)
set_target_properties(benchmark_price_gradients_cev PROPERTIES CUDA_STANDARD 23 CUDA_STANDARD_REQUIRED YES)

add_executable(study_price_gradients_heston_rates EXCLUDE_FROM_ALL tests/price_gradients/heston_rate_study.cu)
target_include_directories(study_price_gradients_heston_rates PRIVATE ${CMAKE_SOURCE_DIR})
target_link_libraries(study_price_gradients_heston_rates PRIVATE ai_factory_runtime)
set_target_properties(study_price_gradients_heston_rates PROPERTIES CUDA_STANDARD 23 CUDA_STANDARD_REQUIRED YES)
