#include "ai_factory/cuda/g2_plus_plus/swaptions.cuh"
#include "ai_factory/common/fixed_income/g2_plus_plus.hpp"
#include "ai_factory/cuda/common/philox.cuh"
#include "ai_factory/cuda/common/reductions.cuh"
#include "ai_factory/cuda/common/runtime.cuh"
namespace ai_factory::cuda {namespace {constexpr int kMaxPayments=20;struct Tag{};
__global__ void kernel(const G2PlusPlusSwaptionRow*rows,std::size_t count,std::size_t paths,MonteCarloOutput*outputs){const auto ri=static_cast<std::size_t>(blockIdx.x);if(ri>=count)return;const auto r=rows[ri];const auto&m=r.model;const auto&p=r.product;__shared__ double ba[kMaxPayments],bbx[kMaxPayments],bby[kMaxPayments];__shared__ fixed_income::G2Transition transition;if(threadIdx.x<p.payment_count){const double maturity=p.expiry+(threadIdx.x+1)*p.accrual_period;ba[threadIdx.x]=fixed_income::g2_bond_price(0,0,p.expiry,maturity,m.mean_reversion_x,m.volatility_x,m.mean_reversion_y,m.volatility_y,m.rho,r.curve.beta0,r.curve.beta1,r.curve.beta2,r.curve.tau);bbx[threadIdx.x]=fixed_income::ou_b(m.mean_reversion_x,maturity-p.expiry);bby[threadIdx.x]=fixed_income::ou_b(m.mean_reversion_y,maturity-p.expiry);}if(threadIdx.x==0)transition=fixed_income::make_g2_transition(m.mean_reversion_x,m.volatility_x,m.mean_reversion_y,m.volatility_y,m.rho,p.expiry);__syncthreads();double sum=0,sumsq=0;for(std::size_t path=threadIdx.x;path<paths;path+=blockDim.x){double x=0,y=0,ix=0,iy=0;fixed_income::apply_g2_transition(transition,rng::standard_normal(r.seed,0U,4U*path),rng::standard_normal(r.seed,0U,4U*path+1U),rng::standard_normal(r.seed,0U,4U*path+2U),rng::standard_normal(r.seed,0U,4U*path+3U),x,y,ix,iy);double annuity=0,end=1;for(int j=0;j<p.payment_count;++j){const double bond=ba[j]*exp(-bbx[j]*x-bby[j]*y);annuity+=p.accrual_period*bond;end=bond;}const double swap=static_cast<double>(p.direction)*(1-end-p.fixed_rate*annuity);const double discount=fixed_income::g2_path_discount(ix,iy,p.expiry,m.mean_reversion_x,m.volatility_x,m.mean_reversion_y,m.volatility_y,m.rho,r.curve.beta0,r.curve.beta1,r.curve.beta2,r.curve.tau);const double payoff=discount*p.notional*fmax(swap,0.0);sum+=payoff;sumsq+=payoff*payoff;}reductions::reduce_block(sum,sumsq);if(threadIdx.x==0){extern __shared__ double shared[];const double n=static_cast<double>(paths),mean=shared[0]/n,var=(shared[blockDim.x]-n*mean*mean)/(n-1);outputs[ri]={mean,sqrt(fmax(var,0.0)/n)};}}
}
void price_g2_plus_plus_swaption_cuda(const G2PlusPlusSwaptionRow*h,std::size_t n,std::size_t paths,MonteCarloOutput*out,CudaTiming*t){auto&w=detail::reusable_cuda_workspace<Tag,2>();auto*r=w.buffer<G2PlusPlusSwaptionRow>(0,n,"G2++ swaption rows");auto*o=w.buffer<MonteCarloOutput>(1,n,"G2++ swaption outputs");detail::check_cuda(cudaMemcpy(r,h,n*sizeof(*h),cudaMemcpyHostToDevice),"copy rows");detail::check_cuda(cudaEventRecord(w.start_event()),"start");kernel<<<static_cast<unsigned>(n),detail::kThreadsPerBlock,2*detail::kThreadsPerBlock*sizeof(double)>>>(r,n,paths,o);detail::check_cuda(cudaGetLastError(),"G2++ swaption kernel");detail::check_cuda(cudaEventRecord(w.stop_event()),"stop");detail::check_cuda(cudaEventSynchronize(w.stop_event()),"sync");float ms=0;detail::check_cuda(cudaEventElapsedTime(&ms,w.start_event(),w.stop_event()),"elapsed");detail::check_cuda(cudaMemcpy(out,o,n*sizeof(*out),cudaMemcpyDeviceToHost),"copy outputs");if(t){t->simulation_ms=ms;t->total_ms=ms;}}
}
