#include "ai_factory/cuda/cir_plus_plus/caplets.cuh"
#include "ai_factory/common/fixed_income/cir_plus_plus.hpp"
#include "ai_factory/cuda/common/philox.cuh"
#include "ai_factory/cuda/common/reductions.cuh"
#include "ai_factory/cuda/common/runtime.cuh"
namespace ai_factory::cuda {namespace {constexpr double kPsi=1.5;struct Tag{};struct Coefficients{std::size_t steps;double dt,decay,omd,vol2,ba,bb;};
__global__ void kernel(const CirPlusPlusCapletRow*rows,std::size_t count,std::size_t paths,double target_dt,MonteCarloOutput*outputs){const auto i=static_cast<std::size_t>(blockIdx.x);if(i>=count)return;const auto r=rows[i];const auto&m=r.model;const auto&p=r.product;__shared__ Coefficients c;if(threadIdx.x==0){const auto rounded=llround(p.fixing_time/target_dt);c.steps=static_cast<std::size_t>(rounded>0?rounded:1);c.dt=p.fixing_time/static_cast<double>(c.steps);c.decay=exp(-m.kappa*c.dt);c.omd=1-c.decay;c.vol2=m.volatility*m.volatility;c.ba=fixed_income::cir_plus_plus_bond_a(p.fixing_time,p.fixing_time+p.accrual_period,m.initial_factor,m.kappa,m.theta,m.volatility,r.curve.beta0,r.curve.beta1,r.curve.beta2,r.curve.tau);c.bb=fixed_income::cir_bond_b(m.kappa,m.volatility,p.accrual_period);}__syncthreads();double sum=0,sumsq=0;for(std::size_t path=threadIdx.x;path<paths;path+=blockDim.x){double factor=m.initial_factor,integral=0;rng::NormalSequence normals(r.seed,path,0U);rng::UniformSequence uniforms(r.seed,path+paths,0U);for(std::size_t step=0;step<c.steps;++step){const double previous=factor,mean=m.theta+(factor-m.theta)*c.decay,var=factor*c.vol2*c.decay*c.omd/m.kappa+m.theta*c.vol2*c.omd*c.omd/(2*m.kappa),psi=var/(mean*mean),z=normals.next(),u=uniforms.next();if(psi<=kPsi){const double inv=1/psi,b2=2*inv-1+sqrt(2*inv)*sqrt(fmax(2*inv-1,0.0)),scale=mean/(1+b2),shift=sqrt(b2)+z;factor=scale*shift*shift;}else{const double probability=(psi-1)/(psi+1),beta=(1-probability)/mean;factor=u<=probability?0.0:log((1-probability)/(1-u))/beta;}integral+=0.5*(previous+factor)*c.dt;}const double bond=c.ba*exp(-c.bb*factor),discount=fixed_income::cir_plus_plus_path_discount(integral,p.fixing_time,m.initial_factor,m.kappa,m.theta,m.volatility,r.curve.beta0,r.curve.beta1,r.curve.beta2,r.curve.tau),payoff=discount*p.notional*fmax(1-(1+p.accrual_period*p.strike)*bond,0.0);sum+=payoff;sumsq+=payoff*payoff;}reductions::reduce_block(sum,sumsq);if(threadIdx.x==0){extern __shared__ double shared[];const double n=static_cast<double>(paths),mean=shared[0]/n,var=(shared[blockDim.x]-n*mean*mean)/(n-1);outputs[i]={mean,sqrt(fmax(var,0.0)/n)};}}
}
void price_cir_plus_plus_caplet_cuda(const CirPlusPlusCapletRow*h,std::size_t n,std::size_t paths,double dt,MonteCarloOutput*out,CudaTiming*t){auto&w=detail::reusable_cuda_workspace<Tag,2>();auto*r=w.buffer<CirPlusPlusCapletRow>(0,n,"caplet rows");auto*o=w.buffer<MonteCarloOutput>(1,n,"caplet outputs");detail::check_cuda(cudaMemcpy(r,h,n*sizeof(*h),cudaMemcpyHostToDevice),"copy rows");detail::check_cuda(cudaEventRecord(w.start_event()),"start");kernel<<<static_cast<unsigned>(n),detail::kThreadsPerBlock,2*detail::kThreadsPerBlock*sizeof(double)>>>(r,n,paths,dt,o);detail::check_cuda(cudaGetLastError(),"CIR++ caplet kernel");detail::check_cuda(cudaEventRecord(w.stop_event()),"stop");detail::check_cuda(cudaEventSynchronize(w.stop_event()),"sync");float ms=0;detail::check_cuda(cudaEventElapsedTime(&ms,w.start_event(),w.stop_event()),"elapsed");detail::check_cuda(cudaMemcpy(out,o,n*sizeof(*out),cudaMemcpyDeviceToHost),"copy outputs");if(t)t->simulation_ms=t->total_ms=ms;}
}
